#!/bin/sh

WORKPATH="/tmp/haivision/"
STATSFILE="$WORKPATH/service_status"

mkdir -p $WORKPATH
rm -fr $STATSFILE

killall -SIGUSR1 service

ccount=1
while [ ! -f $STATSFILE ]; do
   count=$(( $count + 1 ))
   [ $count -le 3 ] || {
      echo -n "{}"
      exit 1
   }
   sleep 1
done

cat $STATSFILE

exit 0

